version: '3'

services:

  api:
    build: "https://github.com/ZPI-2023-IST/API.git#port_change"
    ports:
      - "5002:5002"

  frontend:
    build: "https://github.com/ZPI-2023-IST/Frontend.git"
    ports:
      - "3000:3000"

  rl:
    build: "https://github.com/ZPI-2023-IST/RL.git#integration_different_port"
    ports:
      - "5000:5000"

  freecell-gui:
    build: "https://github.com/ZPI-2023-IST/FreeCell-GUI.git"
    ports:
      - "5005:5005"